name: CI Pipeline

on:
  - push
  - pull_request


jobs:
  lint-format-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run Black (check formatting)
      run: |
        black --check .

    - name: Run isort (check import sorting)
      run: |
        isort --check-only --profile black .

    - name: Run flake8 (lint)
      run: |
        flake8 .

    - name: Run mypy (type check)
      run: |
        mypy .

    - name: Run pytest (unit tests)
      run: |
        pytest --maxfail=1 --disable-warnings -q
